#!/bin/bash

# Nome do perfil AWS CLI para usar
AWS_PROFILE="nome_do_perfil"

# Nome do bucket público de origem e o objeto que você quer copiar
PUBLIC_BUCKET="public-bucket"
OBJECT_NAME="nome_do_objeto"

# Nome do bucket privado de destino
PRIVATE_BUCKET="private-bucket"

# Nome do diretório temporário
TEMP_DIR="./temp_s3_dir"

# Criar o diretório temporário
mkdir -p $TEMP_DIR

# Baixar o objeto do bucket público para o diretório temporário
aws s3 cp s3://$PUBLIC_BUCKET/$OBJECT_NAME $TEMP_DIR/ --no-sign-request

# Fazer upload do objeto para o bucket privado na pasta "upload"
aws s3 cp $TEMP_DIR/$OBJECT_NAME s3://$PRIVATE_BUCKET/upload/ --profile $AWS_PROFILE

# Remover o diretório temporário e seu conteúdo
rm -rf $TEMP_DIR

echo "A cópia foi concluída e o diretório temporário foi removido."
